### ISSUE TITLE
README example output

### ISSUE THREAD

**Issue by mxstbr** [jonathantneal/postcss-to-nest#1]
In the README, the example output looks like this:

``` CSS
.foo {
    @nest & .bar {
        color: blue;

        @nest & .pre {
            color: red;

            @nest &.mon {
                color: white;
            }
        }
    }
}
```

Is there a reason for the space before the `.pre` and the `.bar`, but no space before the `.mon`?
